logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /tmp/webapp.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: time
      time_format: "yyyy-MM-dd' 'HH:mm:ss.SSS"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.severity
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, move_severity]