name: Integration Tests

on: [pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: web_application
      DB_USER: webapplication
      DB_PASSWORD: webapplication

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start

      - name: Create User and Database
          mysql -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';" -uroot -proot
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -uroot -proot
          mysql -e "GRANT ALL PRIVILEGES ON *.* TO '$DB_DATABASE'@'localhost' WITH GRANT OPTION;" -uroot -proot
          mysql -e "FLUSH PRIVILEGES;" -uroot -proot