name: Integration Tests

on: [pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: web_application
      DB_USER: webapplication
      DB_PASSWORD: webapplication

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start

      - name: Create User and Database
        run: |
          mysql -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';" -uroot -proot
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -uroot -proot
          mysql -e "GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'localhost';" -uroot -proot
          mysql -e "FLUSH PRIVILEGES;" -uroot -proot

      - name: Create Tables
        run: |
          mysql -e "USE $DB_DATABASE; CREATE TABLE IF NOT EXISTS users (
              id INT AUTO_INCREMENT PRIMARY KEY,
              username VARCHAR(50) NOT NULL,
              password VARCHAR(50) NOT NULL,
              email VARCHAR(100),
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );" -u$DB_USER -p$DB_PASSWORD

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test with Maven

        run: mvn -B package --file pom.xml
