name: Integration Tests

on: [pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: web_application
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start

      - name: Create User and Database
        run: |
          mysql -e "CREATE USER 'webapplication'@'localhost' IDENTIFIED BY 'webapplication';" -uroot -p
          mysql -e "CREATE DATABASE IF NOT EXISTS web_application;" -uroot -p
          mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'web_application'@'localhost' WITH GRANT OPTION;" -uroot -p
          mysql -e "FLUSH PRIVILEGES;" -uroot -p