name: Packer Continuous Integration

on: [pull_request]

jobs:
  packer_checks:
    name: Packer Template Verification
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: web_application
      DB_USER: webapplication
      DB_PASSWORD: webapplication

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Create webapp directory
        run: mkdir -p packer/webapp
        working-directory: .

      - name: packer ini
        run: packer init gcp.pkr.hcl
        working-directory: ./packer

      - name: packer fmt
        run:  packer fmt gcp.pkr.hcl
        working-directory: ./packer

      - name: packer validate
        run: packer validate -var 'project_id="csye6225-414206"' gcp.pkr.hcl
        working-directory: ./packer