name: Packer CI Build Custom Image

on:
  push:
    branches:
      - main

jobs:
  packer-ci-build-custom-image:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: web_application
      DB_USER: webapplication
      DB_PASSWORD: webapplication

      PROJECT_ID: ${{secrets.PROJECT_ID}}
      SERVICE_ACCOUNT: ${{secrets.SERVICE_ACCOUNT}}
      CLOUD_SQL_INSTANCE: ${{secrets.CLOUD_SQL_INSTANCE}}
      KMS_KEY: ${{secrets.KMS_KEY}}
      VM_KEY: ${{secrets.VM_KEY}}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.PACKER_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start

      - name: Create User and Database
        run: |
          mysql -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';" -uroot -proot
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -uroot -proot
          mysql -e "GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'localhost';" -uroot -proot
          mysql -e "FLUSH PRIVILEGES;" -uroot -proot

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Create Log Directory
        run: |
          sudo mkdir -p /var/log/webapp
          sudo chmod 777 /var/log/webapp

      - name: Run integration tests
        run: mvn test -Dtest=UserRestControllerIntegrationTests

      - name: Build application artifact
        run: |
          mvn clean package

      - name: Zip artifacts
        run: |
          cd target
          zip -r ../webapp.zip *.jar

      - name: Create webapp directory placeholder
        run: mkdir -p packer/webapp
        working-directory: .

      - name: Prepare artifacts for Packer
        run: |
          mv webapp.zip ./packer/webapp

      - name: Build custom image with Packer
        run: |
          packer init .
          packer build -var-file=variables.pkrvars.hcl gcp.pkr.hcl
        working-directory: ./packer

      - name: Get the image name
        run: |
          IMAGE_NAME=$(gcloud compute images list --filter="name~'dev-project-custom-image-.*'" --sort-by="~creationTimestamp" --limit=1 --format="get(name)")
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Generate random password
        run: |
          sudo apt-get install -y pwgen
          PASSWORD=$(pwgen -s 8 1)
          echo "RANDOM_PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Create startup script
        run: |
          sudo echo '#!/bin/bash' > startup-script.sh
          sudo echo 'set -e' >> startup-script.sh
          sudo echo "sudo echo \"spring.datasource.url=jdbc:mysql://google/webapp?cloudSqlInstance=${{env.CLOUD_SQL_INSTANCE}}&socketFactory=com.google.cloud.sql.mysql.SocketFactory\" > /opt/webapp/application.properties" >> startup-script.sh
          sudo echo "sudo echo \"spring.cloud.gcp.sql.database-name=webapp\" >> /opt/webapp/application.properties" >> startup-script.sh
          sudo echo "sudo echo \"spring.datasource.username=webapp\" >> /opt/webapp/application.properties" >> startup-script.sh
          sudo echo "sudo echo \"spring.sql.init.mode=never\" >> /opt/webapp/application.properties" >> startup-script.sh
          sudo echo "sudo echo \"spring.datasource.password=${{env.RANDOM_PASSWORD}}\" >> /opt/webapp/application.properties" >> startup-script.sh
          sudo echo "sudo echo \"GOOGLE_CLOUD_PROJECT=${{env.PROJECT_ID}}\" >> /opt/webapp/application.properties" >> startup-script.sh
          sudo echo "sudo echo \"PUBSUB_TOPIC=verify_email\" >> /opt/webapp/application.properties" >> startup-script.sh
          sudo echo "sudo chown -R csye6225:csye6225 /opt/webapp/application.properties" >> startup-script.sh

      - name: Create new instance template
        run: |
          gcloud compute instance-templates create dev-project-instance-template-${GITHUB_SHA:0:8} \
            --image=${{ env.IMAGE_NAME }} \
            --region=us-west1 \
            --machine-type=e2-highmem-2 \
            --tags=allow-https,allow-health-check,disallow-ssh \
            --metadata-from-file startup-script=startup-script.sh \
            --service-account=${{ env.SERVICE_ACCOUNT }} \
            --scopes=cloud-platform \
            --boot-disk-type=pd-standard \
            --boot-disk-kms-key=${{ env.KMS_KEY }} \
            --network=vpc \
            --subnet=webapp

      - name: Update instance group with new template
        run: |
          gcloud compute instance-groups managed set-instance-template webapp-igm \
          --project=${{env.PROJECT_ID}} \
          --zone=us-west1-a \
          --template=dev-project-instance-template-${GITHUB_SHA:0:8}

      - name: Recreate instances in managed instance group
        run: |       
          gcloud compute instance-groups managed rolling-action start-update webapp-igm \
          --version=template=dev-project-instance-template-${GITHUB_SHA:0:8} \
          --type=proactive \
          --zone=us-west1-a 

      - name: Wait for instances to be recreated
        run: |
          gcloud compute instance-groups managed wait-until webapp-igm \
          --version-target-reached \
          --zone=us-west1-a