name: Packer Custom Image Build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.PACKER_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Run integration tests
        run: mvn test -Dtest=UserRestControllerIntegrationTests

      - name: Build application artifact
        run: |
          mvn clean package

      - name: Prepare artifacts for Packer
        run: |
          mkdir -p ./packer/artifacts
          cp ./target/*.jar ./packer/artifacts

      - name: Build custom image with Packer
        run: |
          packer init .
          packer build -var 'project_id=csye6225-414206' ./packer/gcp.pkr.hcl
        working-directory: ./packer
