name: pull-request-status-check

on: [pull_request]

jobs:
  pull-request-status-check:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: webapplication
          MYSQL_ROOT_PASSWORD: webapplication
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set up sql server
        run: sudo mysql -h 127.0.0.1 --port 8888 -uwebapplication -pwebapplication
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
      - name: Build with Maven
        run: ./mvnw package
