name: Pull Request Status Check

on: [pull_request]

jobs:
  pull-request-status-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
      - name: Build with Maven
        run: ./mvnw package -DskipTests


